POST http://localhost:3001/api/stocks
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im51bWJlcnMiLCJpZCI6MSwiaWF0IjoxNjg1MDgyMDE5LCJleHAiOjE2ODUwODU2MTl9.Y2lSQmUL5RiAtYltQdBFsZ8vaPR_W9DyijSGlNatZJo

{
  "symbol": "TSLA",
  "quantity": 10
}